### ISSUE TITLE
Add Wifi_RxCallBack() on usart interrupt routine

### ISSUE THREAD

**Issue by easy-fw** [nimaltd/ESP8266#1]
Hi, great work you have done here. Could you please show me how to put the Wifi Callback on the uart routine. I am trying by myself  but cant seem to be able.

Thank you very much

**Comment by nimaltd** [comment]
Hi. I post example soon.

**Comment by nimaltd** [comment]
But you can see an example on sim800 library.

**Comment by easy-fw** [comment]
Thank you very much, i saw the example and got it.
Thanks again
