### ISSUE TITLE
usart interrupt routin

### ISSUE THREAD

**Issue by mue-barakat** [nimaltd/ESP8266#3]
i followed all your steps but i don't know where is  usart interrupt routin to add Wifi_RxCallBack() to
can you point me to it ?

**Comment by nimaltd** [comment]
when you enable an interrupd on cubemx. you can open "stm32f4xx_it.c" file for f4 serries.
add Wifi_RxCallBack()  in below of a function in usart interrupt.
void USART1_IRQHandler(void)
{
  /* USER CODE BEGIN USART1_IRQn 0 */

  /* USER CODE END USART1_IRQn 0 */
  HAL_UART_IRQHandler(&huart1);
  /* USER CODE BEGIN USART1_IRQn 1 */
	Wifi_RxCallBack();
  /* USER CODE END USART1_IRQn 1 */
}
